11-rails-rest-form/doctor-app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'doctors#home'

  resources :doctors
  resources :patients

  resources :appointments, only: [ :index, :new, :create ]
end

11-rails-rest-form/doctor-app/app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient
end

11-rails-rest-form/doctor-app/app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :appointments
  has_many :patients, through: :appointments

  validates :name, presence: true 
  validates :name, uniqueness: { case_sensitive: false }
  validates :specialty, presence: true

  validate :name_has_to_have_md_at_the_end


  def name_and_specialty
    "#{name} (#{specialty})"
  end


  private

  def name_has_to_have_md_at_the_end
    suffix = name.split(' ')[-1]
    if suffix != "M.D."
      errors.add(:name, "You have to have M.D. as a suffix to be a REAL doctor.")
    end
  end
end

11-rails-rest-form/doctor-app/app/models/patient.rb
class Patient < ApplicationRecord
  has_many :appointments
  has_many :doctors, through: :appointments
  
  validates :name, presence: true
end

11-rails-rest-form/doctor-app/app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

  def new
    @doctors = Doctor.all
    @patients = Patient.all
    @appointment = Appointment.new
    render :new
  end

  def create
    Appointment.create(appointment_params)
    redirect_to new_appointment_path
  end

  def appointment_params
    params.require(:appointment).permit(:doctor_id, :patient_id, :illness)
  end
end

11-rails-rest-form/doctor-app/app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :find_doctor, only: [:show, :edit, :destroy, :update]

  def home
    render :home
  end

  def index
    @doctors = Doctor.all
    render :index
  end

  def show
    render :show
  end

  def new
    @doctor = Doctor.new
    render :new
  end

  def create
    @doctor = Doctor.new(doctor_params)
    if @doctor.save
      redirect_to doctor_path(@doctor)  #"/doctors/#{@doctor.id}"
    else
      flash[:errors] = @doctor.errors.full_messages
      redirect_to new_doctor_path
    end
  end

  def edit
    render :edit
  end

  def update
    @doctor.update(doctor_params)
    redirect_to doctor_path(@doctor)
  end


  def destroy
    @doctor.destroy
    redirect_to doctors_path
  end



  private
  
  def find_doctor
    @doctor = Doctor.find(params[:id])
  end

  def doctor_params
    params.require(:doctor).permit(:name, :specialty)
  end
end

11-rails-rest-form/doctor-app/app/controllers/patients_controller.rb
class PatientsController < ApplicationController

  before_action :find_patient, only: [:show, :edit, :update, :destroy]

  def index
    # show all the patients
    @patients = Patient.all
    render :index
  end

  def show
    # show info about 1 patient
    render :show
  end

  def new
    # show a form to help create a patient
    @patient = Patient.new
    render :new
  end

  def edit
    # show a form to help edit a patient
    render :edit
  end

  def create
    # takes params from the new form
    # creates a patient and saves it using those params
    @patient = Patient.create(patient_params)
    redirect_to patient_path(@patient)
  end

  def update
    # takes params from edit form
    # updates the patient and saves it using those params
    @patient.update(patient_params)
    redirect_to patient_path(@patient)
  end

  def destroy
    # finds a patient and destroys it
    @patient.destroy
    redirect_to patients_path
  end

  private

  def find_patient
    @patient = Patient.find(params[:id])
  end

  def patient_params
    params.require(:patient).permit(:name, :insurance, :age)
  end
end

11-rails-rest-form/doctor-app/app/helpers/appointments_helper.rb
module AppointmentsHelper
end

11-rails-rest-form/doctor-app/app/helpers/doctors_helper.rb
module DoctorsHelper
end

11-rails-rest-form/doctor-app/app/helpers/patients_helper.rb
module PatientsHelper
end

11-rails-rest-form/doctor-app/app/views/appointments/new.html.erb
<%= form_for(@appointment) do |f| %>
  <%= f.label :doctor_id %>
  <%= f.collection_select(:doctor_id, @doctors, :id, :name_and_specialty) %>
  <!--
  <select name="appointment[doctor_id]">
  <%# @doctors.each do |d| %>
    <option value="<%# d.id %>"><%# d.name %></option>
  <%# end %>
  </select>
  -->

  <%= f.label :patient_id %>
  <%= f.collection_select(:patient_id, @patients, :id, :name) %>
  <!--
  <select name="appointment[patient_id]">
  <%# @patients.each do |p| %>
    <option value="<%# p.id %>"><%# p.name %></option>
  <%# end %>
  </select>
  -->

  <%= f.label :illness %>
  <%= f.text_field :illness %>

  <%= f.submit %>
<% end %>

11-rails-rest-form/doctor-app/app/views/doctors/edit.html.erb
<h1>Edit Doctor</h1>

<%= form_for @doctor do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :specialty %>
  <%= f.text_field :specialty %>
  
  <%= f.submit %>
<% end %>

11-rails-rest-form/doctor-app/app/views/doctors/home.html.erb
<h1>Welcome to the Doctor App</h1>

11-rails-rest-form/doctor-app/app/views/doctors/index.html.erb
<h1>All Doctors:</h1>
<ul>
<% @doctors.each do |doctor| %>
  <li> <%= link_to(doctor.name, doctor) %> </li>
<% end %>
</ul>

11-rails-rest-form/doctor-app/app/views/doctors/new.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <p><%= error %></p>
  <% end %>
<% end %>

<%= form_for @doctor do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :specialty %>
  <%= f.text_field :specialty %>

  <%= f.submit %>
<% end %>


<%# form_tag(doctors_path) do %>
  <%# text_field_tag :"doctor[name]" %>
  <%# text_field_tag :"doctor[specialty]" %>
  <%# submit_tag "create doctor" %>
<%# end %>

11-rails-rest-form/doctor-app/app/views/doctors/show.html.erb
<h1>Doctor Bio:</h1>
<p><%= @doctor.name %> (<%= @doctor.specialty %>)</p>


<%= link_to "Delete Doctor", doctor_path(@doctor), method: :delete %>
<%= link_to "Edit Doctor", edit_doctor_path(@doctor) %>

11-rails-rest-form/doctor-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoctorApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

11-rails-rest-form/doctor-app/app/views/patients/edit.html.erb
<h1>Edit Patient</h1>

<%= form_for @patient do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :age %>
  <%= f.text_field :age %>

  <%= f.label :insurance %>
  <%= f.text_field :insurance %>

  <%= f.submit %>
<% end %>

11-rails-rest-form/doctor-app/app/views/patients/index.html.erb
<h1>All Patients:</h1>
<ul>
<% @patients.each do |patient| %>
  <li> <%= link_to(patient.name, patient) %> </li>
<% end %>
</ul>

11-rails-rest-form/doctor-app/app/views/patients/new.html.erb
<h1>New Patient</h1>

<%= form_for @patient do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :age %>
  <%= f.text_field :age %>

  <%= f.label :insurance %>
  <%= f.text_field :insurance %>

  <%= f.submit %>
<% end %>

11-rails-rest-form/doctor-app/app/views/patients/show.html.erb
<h1>patient Bio:</h1>
<p><%= @patient.name %></p>
<p>Insurance? <%= @patient.insurance %></p>
<p>Age: <%= @patient.age %></p>


<%= link_to "Delete patient", patient_path(@patient), method: :delete %>
<%= link_to "Edit patient", edit_patient_path(@patient) %>